### PR TITLE
NVMe MI basic command support

### PR DESCRIPTION
**Pull request by amboar**
This applies the series that was merged upstream in https://github.com/openbmc/dbus-sensors/compare/33703af797949b47375086988daeac89b47b5db1...587941d0af66ac183984c832c4f0b2958c8daa38

### CODE REVIEW

**Comment by rfrandse** [comment]
For reference Upstream commits:
< 587941d nvmesensor: Enable by default Author:Andrew Jeffery
< 88122e7 nvmesensor: Disable NVMe MI MCTP by default Author:Andrew Jeffery
< 6f25e7e nvmesensor: Introduce nvme-mi-mctp build feature Author:Andrew Jeffery
< e3e3c97 nvmesensor: Support the NVMe MI basic management command Author:Andrew Jeffery
< e3b23c0 meson: Disable PSABI warning Author:Andrew Jeffery

**Comment by geissonator** [comment]
add to approvelist

**Comment by geissonator** [comment]
jenkins run tests please

**Comment by rfrandse** [comment]
rebase done to pick up this function in https://github.com/ibm-openbmc/dbus-sensors/pull/6

**Pull request closed without merging**
