### PR TITLE
hwmontempsensor: slot powered sensors: Check for valid Bus/Address fields

### PR DESCRIPTION
**Pull request by spinler**
The code that handles sensors on PCIe slot power should validate that the Bus/Address D-Bus fields are valid uint64_t values before trying to get them, because if a card is plugged in an unsupported slot those values will be strings, like "$bus" or "$address".

The other commit fixes something noticed in some testing.

Fix for SW556218

### CODE REVIEW

**Comment by spinler** [comment]
I added the must fix template to see if it also needs to go into a 1020 service pack.

**Review by smccarney — APPROVED** [review]
Have the same changes been made upstream?

**Comment by spinler** [comment]
This is all downstream code, since it relies on some PIM items to work.  If/when we converge on entity-manager I hope make an upstreamable version.

**Comment by spinler** [comment]
failed a clang-tidy-14 check in a testcase for some code that ibm doesn't even use...

**Review by smccarney — APPROVED** [review]

**Pull request merged**
