### PR TITLE
1020-history-perserving-rebase

### PR DESCRIPTION
**Pull request by rfrandse**
History perserving rebase

### CODE REVIEW

**Comment by rfrandse** [comment]
Merge conflict in src/HwmonTempMain.cpp

00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 390) <<<<<<< HEAD
20bf2c1c (Matt Spinler         2021-09-14 11:07:07 -0500 391) 
20bf2c1c (Matt Spinler         2021-09-14 11:07:07 -0500 392)     // Watch for entity-manager to remove configuration interfaces
20bf2c1c (Matt Spinler         2021-09-14 11:07:07 -0500 393)     // so the corresponding sensors can be removed.
20bf2c1c (Matt Spinler         2021-09-14 11:07:07 -0500 394)     auto ifaceRemovedMatch = std::make_unique<sdbusplus::bus::match::match>(
20bf2c1c (Matt Spinler         2021-09-14 11:07:07 -0500 395)         static_cast<sdbusplus::bus::bus&>(*systemBus),
20bf2c1c (Matt Spinler         2021-09-14 11:07:07 -0500 396)         "type='signal',member='InterfacesRemoved',arg0path='" +
20bf2c1c (Matt Spinler         2021-09-14 11:07:07 -0500 397)             std::string(inventoryPath) + "/'",
20bf2c1c (Matt Spinler         2021-09-14 11:07:07 -0500 398)         [&sensors](sdbusplus::message::message& msg) {
20bf2c1c (Matt Spinler         2021-09-14 11:07:07 -0500 399)             interfaceRemoved(msg, sensors);
20bf2c1c (Matt Spinler         2021-09-14 11:07:07 -0500 400)         });
20bf2c1c (Matt Spinler         2021-09-14 11:07:07 -0500 401) 
20bf2c1c (Matt Spinler         2021-09-14 11:07:07 -0500 402)     matches.emplace_back(std::move(ifaceRemovedMatch));
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 403) =======
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 404)     // When power turns on, create event logs for failing sensors.
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 405)     PowerStateCallback::Callback powerChanged = [&sensors](bool powerState) {
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 406)         if (powerState)
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 407)         {
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 408)             // Forget about previous fails.
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 409)             HwmonTempSensor::clearFailedDevices();
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 410) 
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 411)             for (const auto& [name, sensor] : sensors)
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 412)             {
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 413)                 if ((sensor->errCount >= errorThreshold) &&
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 414)                     std::isnan(sensor->value))
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 415)                 {
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 416)                     sensor->createEventLog();
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 417)                 }
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 418)             }
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 419)         }
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 420)     };
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 421) 
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 422)     PowerStateCallback::addCallback(powerChanged);
00000000 (Not Committed Yet    2021-09-27 10:47:06 -0500 423) >>>>>>> ef38670... hwmontemp: Create event logs for failed reads

Resolution use both changes : 

    // Watch for entity-manager to remove configuration interfaces
    // so the corresponding sensors can be removed.
    auto ifaceRemovedMatch = std::make_unique<sdbusplus::bus::match::match>(
        static_cast<sdbusplus::bus::bus&>(*systemBus),
        "type='signal',member='InterfacesRemoved',arg0path='" +
            std::string(inventoryPath) + "/'",
        [&sensors](sdbusplus::message::message& msg) {
            interfaceRemoved(msg, sensors);
        });

    matches.emplace_back(std::move(ifaceRemovedMatch));

    // When power turns on, create event logs for failing sensors.
    PowerStateCallback::Callback powerChanged = [&sensors](bool powerState) {
        if (powerState)
        {
            // Forget about previous fails.
            HwmonTempSensor::clearFailedDevices();

            for (const auto& [name, sensor] : sensors)
            {
                if ((sensor->errCount >= errorThreshold) &&
                    std::isnan(sensor->value))
                {
                    sensor->createEventLog();
                }
            }
        }
    };

    PowerStateCallback::addCallback(powerChanged);

**Comment by geissonator** [comment]
jenkins run tests please

**Review by amboar — APPROVED** [review]
Github's commit view makes the result look weird, but inspecting Reed's branch locally suggests it's fine.

**Comment by rfrandse** [comment]
picked up the "fix code formatting" with https://github.com/ibm-openbmc/dbus-sensors/pull/6

**Pull request closed without merging**
